services:
  db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=houseops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - house-ops-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AllowedOrigins=http://localhost:3000
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=houseops_db;Username=user;Password=password
    networks:
      - house-ops-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5001/api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api
    depends_on:
      - backend
    networks:
      - house-ops-network

networks:
  house-ops-network:
    driver: bridge

volumes:
  postgres_data:
